## Numpy - Activity file 1:

In [20]:
import numpy as np

In [ ]:
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2) #2D array with 2 rows and 3 columns

[[1 2 3]
 [4 5 6]]


In [26]:
arr3 = np.array((1,2,3,4,5))
print(arr3) #1D array with 5 elements

[1 2 3 4 5]


In [15]:
arr4 = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])

In [18]:
arr4.shape    # 3 rows and 5 columns

(3, 5)

In [17]:
print(arr4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [5]:
import Numpy as np

SPECIAL ARRAYS:

In [9]:
import numpy as np
arr0 = np.zeros((3,5), dtype='int')
print(arr0)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [10]:
arr1s = np.ones((2,8), dtype='float')
print(arr1s)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [12]:
arrfull = np.full((4,4),7)    #an array with 4x4 shape and all values are 7
print(arrfull)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [13]:
arrId = np.eye(4)   #4x4 identity matrix
print(arrId)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [29]:
arrSeq = np.arange(5)  # array with values from 0 to 4
arrSeq

array([0, 1, 2, 3, 4])

In [33]:
arrSeq2 = np.arange(2,10,2)  # array with values from 2 to 9 with step size of 2
arrSeq2

array([2, 4, 6, 8])

“Create an array of 20 equally spaced numbers starting from 1 and ending at 3 (including both).”

In [34]:
equally_spaced_values = np.linspace(1,3,20) 
equally_spaced_values

array([1.        , 1.10526316, 1.21052632, 1.31578947, 1.42105263,
       1.52631579, 1.63157895, 1.73684211, 1.84210526, 1.94736842,
       2.05263158, 2.15789474, 2.26315789, 2.36842105, 2.47368421,
       2.57894737, 2.68421053, 2.78947368, 2.89473684, 3.        ])

In [42]:
arr_random = np.random.rand(3,4)  #3x4 array with random values between 0 and 1

In [44]:
arr_random    #any random values it changes everytime you run

array([[0.87802659, 0.73528106, 0.09207311, 0.11494459],
       [0.09792145, 0.38657235, 0.37276293, 0.10145275],
       [0.55391505, 0.84897088, 0.80739542, 0.80415047]])

In [48]:
np.random.randn(3,4) #3x4 array with random values from standard normal distribution

array([[-0.10369843, -0.59878909, -0.18890614,  0.16286664],
       [-1.07824905,  0.70526977, -0.89448242, -0.10814689],
       [-0.72804494, -0.304758  ,  1.12550292, -0.97270243]])

In [49]:
np.random.randint(5,10, size=(3,4))  #3x4 array with random integers between 5 and 9

array([[6, 9, 7, 6],
       [8, 8, 6, 6],
       [9, 7, 9, 5]])

In [54]:
arrA = np.array([1.2,2.3,3.9])
arrA = arrA.astype('int')  #converting float array to int array
print(arrA)

[1 2 3]


In [1]:
print("Hello, World!")

Hello, World!
