## Array Operations and Broadcasting:

In [1]:
import numpy as np 

In [2]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

In [3]:
print(a1 + a2)  # Element-wise addition
print(a1 - a2)  # Element-wise subtraction
print(a1 * a2)  # Element-wise multiplication
print(a1 / a2)  # Element-wise division

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
a1 + 10 # Broadcasting: add 10 to each element of a1

array([11, 12, 13])

In [5]:
a2 - 1 # Broadcasting: subtract 1 from each element of a2

array([3, 4, 5])

In [6]:
a2 * 3 # Broadcasting: multiply each element of a2 by 3

array([12, 15, 18])

In [8]:
arr2 = np.array([1,4,9,16])
print(np.sqrt(arr2))  # Element-wise square root
print(np.log(arr2))   # Element-wise natural logarithm
print(np.exp(arr2))   # Element-wise exponential
print(np.sin(arr2))   # Element-wise sine
print(np.cos(arr2))  # Element-wise cosine



[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332]
[ 0.54030231 -0.65364362 -0.91113026 -0.95765948]


In [25]:
arr4 = np.array([[10,30,50],[25,66,34]])
np.sum(arr4)

np.int64(215)

In [26]:
np.sum(arr4, axis=0)  # Sum along columns

array([35, 96, 84])

In [27]:
np.sum(arr4, axis=1)  # Sum along rows

array([ 90, 125])

In [28]:
np.mean(arr4)  # Mean of all elements
np.max(arr4)   # Maximum element
np.min(arr4)   # Minimum element
np.std(arr4)   # Standard deviation of all elements

np.float64(17.94822801529134)

In [32]:
arr5 = np.array([1,3,5],
                [3,5,6])
arr6 = np.array([7,8,9])

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [31]:
np.sum(arr5,arr6)  # Element-wise addition of arr5 and arr6

NameError: name 'arr5' is not defined